server:
  port: 7001
  servlet:
    context-path: /coupon-user

spring:
  application:
    name: eureka-client-coupon-user
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    #    url: jdbc:mysql://127.0.0.1:3306/yaien_coupon_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true   8.0版本
    url: jdbc:mysql://127.0.0.1:3306/cloam_coupon_data?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: CloamCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000
  mail:
    host: smtp.163.com
    username: yaien_6530@163.com
    password: BQLOHLFXQMDHBPCY
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# ------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: cloam-coupon-template
    groupId: cloam-coupon-service
    artifactId: coupon-user
    version: 1.0-SNAPSHOT

# ------------------------------------------------------------------------------------------------------

logging:
  level:
    com.yaien.coupon: debug